# shellcheck shell=bash
# ops env init|check|edit <env>

cmd_env() {
  local sub="${1:-}"
  shift || true
  case "$sub" in
    init) env_init "$@" ;;
    check) env_check "$@" ;;
    edit) env_edit "$@" ;;
    *) die "usage: ops env init|check|edit <env>" ;;
  esac
}

# Ports per hosted environment. Distinct from dev (27017…) and the QA test
# stack (27018…) so a box can run any of them side by side.
hosted_ports() {
  case "$1" in
    qa) echo "3100 27118 6480 9102 9103" ;;
    prod) echo "3200 27119 6481 9104 9105" ;;
    *) die "hosted environments are qa and prod" ;;
  esac
}

# Values worth carrying over from an existing env file: the ones a human set
# by hand. Never the database or Redis credentials — a hosted stack starts with
# its own, and data moves with `ops backup` / `ops restore`, not with passwords.
CARRY_KEYS=(APP_URL S3_ENDPOINT STRIPE_SECRET_KEY STRIPE_WEBHOOK_SECRET STRIPE_CONNECT_WEBHOOK_SECRET
  STRIPE_PRICE_PREMIUM_MONTHLY STRIPE_PRICE_PREMIUM_ANNUAL STRIPE_CONNECT_COUNTRIES
  SMTP_HOST SMTP_PORT SMTP_USER SMTP_PASS MAIL_FROM NEXT_PUBLIC_DOCS_URL)

env_init() {
  local env="" from=""
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --from) from="$2"; shift 2 ;;
      *) env="$1"; shift ;;
    esac
  done
  [[ "$env" == dev ]] && die "dev env files come from \`npm run setup\`, not ops"
  case "$env" in
    qa | prod) OPS_ENV="$env" ;;
    production) OPS_ENV=prod ;;
    *) die "usage: ops env init qa|prod [--from <existing env file>]" ;;
  esac
  local shared="$GRAFT_ROOT/$OPS_ENV/shared" file
  file="$shared/.env"
  [[ -d "$shared" ]] || die "$shared does not exist — run \`ops host init $OPS_ENV\` first"
  [[ -e "$file" ]] && die "$file already exists — edit it with \`ops env edit $OPS_ENV\`, or move it away to regenerate"
  [[ -z "$from" || -r "$from" ]] || die "cannot read $from"

  local port mongo_port redis_port s3_port s3_console app_env db root_pw app_pw redis_pw s3_secret
  read -r port mongo_port redis_port s3_port s3_console < <(hosted_ports "$OPS_ENV")
  app_env="$OPS_ENV"
  [[ "$OPS_ENV" == prod ]] && app_env=production
  db="graft_$OPS_ENV"
  root_pw="$(gen_secret)"
  app_pw="$(gen_secret)"
  redis_pw="$(gen_secret)"
  s3_secret="$(gen_secret)"

  umask 077
  cat >"$file" <<EOF
# Graft hosted environment: $OPS_ENV. Generated by \`ops env init\` on $(date -Is).
# The only copy of these secrets. Mode 600, outside every release, never in git.
# Values marked __set_me__ must be filled in; \`ops env check $OPS_ENV\` lists them.

APP_ENV=$app_env
NODE_ENV=production
PORT=$port
# Public base URL, https, no trailing slash. Every email link, invite and Stripe
# return URL is built from it. Read once at startup: \`ops app $OPS_ENV restart\` after a change.
APP_URL=__set_me__

# ── MongoDB (container, 127.0.0.1 only) ──────────────────────────────────────
MONGO_DB=$db
MONGO_PORT=$mongo_port
MONGO_ROOT_USER=graft_root
MONGO_ROOT_PASSWORD=$root_pw
MONGO_APP_USER=graft_app
MONGO_APP_PASSWORD=$app_pw
MONGODB_URI=mongodb://graft_app:$app_pw@127.0.0.1:$mongo_port/$db?authSource=$db&directConnection=true
# Set by \`ops support $OPS_ENV grant-readonly\`; support lookups use it instead of the app user.
# SUPPORT_MONGODB_URI=

# ── Redis ─────────────────────────────────────────────────────────────────────
REDIS_PORT=$redis_port
REDIS_PASSWORD=$redis_pw
REDIS_URL=redis://:$redis_pw@127.0.0.1:$redis_port

# ── Object storage (MinIO container) ─────────────────────────────────────────
# S3_ENDPOINT is baked into presigned URLs the *browser* uses, so it must be a
# public URL that reaches MinIO's API port ($s3_port), e.g. a second funnel:
#   tailscale funnel --bg --https=8443 $s3_port   →   https://<host>.<tailnet>.ts.net:8443
S3_ENDPOINT=__set_me__
S3_REGION=us-east-1
S3_BUCKET=graft-$OPS_ENV-media
S3_ACCESS_KEY_ID=graft_media
S3_SECRET_ACCESS_KEY=$s3_secret
S3_FORCE_PATH_STYLE=true
S3_PORT=$s3_port
S3_CONSOLE_PORT=$s3_console

# ── Auth ──────────────────────────────────────────────────────────────────────
JWT_PRIVATE_KEY_PATH=$shared/keys/jwt-private.pem
JWT_PUBLIC_KEY_PATH=$shared/keys/jwt-public.pem

# ── Stripe ($([[ "$OPS_ENV" == prod ]] && echo "LIVE mode: sk_live_…" || echo "test mode: sk_test_…")) ─────────────────
# Two dashboard webhook endpoints, two different secrets (README "Hosted QA").
STRIPE_SECRET_KEY=__set_me__
STRIPE_WEBHOOK_SECRET=__set_me__
STRIPE_CONNECT_WEBHOOK_SECRET=__set_me__
STRIPE_PRICE_PREMIUM_MONTHLY=__set_me__
STRIPE_PRICE_PREMIUM_ANNUAL=__set_me__

# ── Email (Gmail App Password, one per environment) ──────────────────────────
# Unset = every email is only printed to the app log.
# SMTP_HOST=smtp.gmail.com
# SMTP_PORT=465
# SMTP_USER=
# SMTP_PASS=
# MAIL_FROM="Graft <you@gmail.com>"
EOF
  chmod 600 "$file"
  ok "wrote $file (mode 600)"

  if [[ -n "$from" ]]; then
    local key value carried=()
    for key in "${CARRY_KEYS[@]}"; do
      value="$(env_get "$key" "$from")"
      [[ -n "$value" ]] || continue
      # MAIL_FROM carries spaces and angle brackets; quote it the way dotenv expects.
      [[ "$value" == *" "* ]] && value="\"$value\""
      env_set "$key" "$value" "$file"
      carried+=("$key")
    done
    ok "carried over from $from: ${carried[*]:-nothing}"
  fi
  echo
  info "next: $(bold "ops env edit $OPS_ENV") to fill the __set_me__ values, then $(bold "ops env check $OPS_ENV")"
}

env_edit() {
  ops_env "${1:-}"
  "${EDITOR:-nano}" "$OPS_ENV_FILE"
  env_check "$OPS_ENV" || true
}

# The rules here are each something that went wrong once (devops/README.md).
env_check() {
  ops_env "${1:-}"
  local problems=0 warnings=0 v app_url s3
  _bad() { fail "$*"; problems=$((problems + 1)); }
  _meh() { warn "$*"; warnings=$((warnings + 1)); }
  info "checking $(bold "$OPS_ENV_FILE") ($OPS_MODE)"

  # Permissions: secrets readable by anyone else on the box is a finding.
  local mode
  mode="$(stat -c '%a' "$OPS_ENV_FILE")"
  [[ "$mode" == 600 || "$mode" == 400 ]] || _bad "mode is $mode — run: chmod 600 $OPS_ENV_FILE"

  local key
  for key in APP_ENV MONGODB_URI REDIS_URL APP_URL JWT_PRIVATE_KEY_PATH JWT_PUBLIC_KEY_PATH \
    S3_ENDPOINT S3_BUCKET S3_ACCESS_KEY_ID S3_SECRET_ACCESS_KEY STRIPE_SECRET_KEY; do
    v="$(env_get "$key")"
    if [[ -z "$v" ]]; then
      _bad "$key is not set"
    elif [[ "$v" == __set_me__ || "$v" == __generated__ ]]; then
      _bad "$key still says $v"
    fi
  done

  # APP_ENV must match the environment it is used as.
  v="$(env_get APP_ENV)"
  local want="$OPS_ENV"
  [[ "$OPS_ENV" == prod ]] && want=production
  [[ -z "$v" || "$v" == "$want" ]] || _bad "APP_ENV=$v but this is the $OPS_ENV environment (want $want)"

  # APP_URL: public base for every link the app emails or hands to Stripe.
  app_url="$(env_get APP_URL)"
  if [[ "$app_url" == */ ]]; then _bad "APP_URL ends with '/' — links come out as //path"; fi
  local local_url=0
  [[ "$app_url" =~ ^https?://(localhost|127\.0\.0\.1)(:|/|$) ]] && local_url=1
  if [[ "$OPS_MODE" == hosted ]]; then
    ((local_url)) && _bad "APP_URL is $app_url — a hosted environment needs its public URL"
    [[ "$app_url" == https://* ]] || _bad "APP_URL must be https (session cookies are always Secure)"
  fi

  # S3_ENDPOINT goes into presigned URLs the *browser* follows (pi QA 2026-10-08).
  s3="$(env_get S3_ENDPOINT)"
  if ((!local_url)) && [[ "$s3" =~ ^https?://(localhost|127\.0\.0\.1)(:|/|$) ]]; then
    _bad "S3_ENDPOINT is $s3 but APP_URL is public — uploads and images break on every other device"
  fi

  # Stripe: right mode for the environment, no fixtures in a real one.
  local sk wh whc
  sk="$(env_get STRIPE_SECRET_KEY)"
  wh="$(env_get STRIPE_WEBHOOK_SECRET)"
  whc="$(env_get STRIPE_CONNECT_WEBHOOK_SECRET)"
  case "$OPS_ENV:$sk" in
    prod:sk_live_* | prod:rk_live_*) ;;
    prod:*) _bad "production needs a live-mode key (sk_live_…), found ${sk:0:8}…" ;;
    *:sk_live_* | *:rk_live_*) _bad "a LIVE Stripe key in $OPS_ENV — real cards would be charged" ;;
  esac
  if [[ "$OPS_MODE" == hosted ]]; then
    [[ "$sk" == *dummy* ]] && _bad "STRIPE_SECRET_KEY is the local dummy"
    [[ "$wh" == whsec_qa_fixture_only_2026 ]] && _bad "STRIPE_WEBHOOK_SECRET is the Bruno fixture secret"
    [[ -n "$wh" && "$wh" != __set_me__ && "$wh" == "$whc" ]] &&
      _meh "both webhook secrets are equal — dashboard endpoints have different ones (only the Stripe CLI shares one)"
    v="$(env_get STRIPE_PRICE_PREMIUM_MONTHLY)"
    [[ "$v" == price_local_dummy* || "$v" == __set_me__ || -z "$v" ]] && _bad "STRIPE_PRICE_PREMIUM_MONTHLY is not a real price id"
  fi

  # Email.
  if [[ -n "$(env_get SMTP_HOST)" ]]; then
    [[ -n "$(env_get SMTP_USER)" && -n "$(env_get SMTP_PASS)" ]] || _bad "SMTP_HOST is set but SMTP_USER/SMTP_PASS are not"
  elif [[ "$OPS_ENV" == prod ]]; then
    _bad "no SMTP in production — verification emails would only be logged"
  elif [[ "$OPS_MODE" == hosted ]]; then
    _meh "no SMTP — emails are only printed to the app log (\`ops logs $OPS_ENV app | grep mail.logged\`)"
  fi

  # Runtime mode.
  if [[ "$OPS_ENV" == prod && "$(env_get NODE_ENV)" != production ]]; then
    _bad "NODE_ENV must be production in prod"
  fi
  [[ "$(env_get NODE_ENV)" == development && "$OPS_MODE" == hosted ]] &&
    _bad "NODE_ENV=development on a hosted box (it also breaks \`next build\`)"

  # Key material the paths point at.
  for key in JWT_PRIVATE_KEY_PATH JWT_PUBLIC_KEY_PATH; do
    v="$(env_get "$key")"
    [[ -z "$v" ]] && continue
    [[ "$v" == /* ]] || v="$OPS_APP_DIR/$v"
    [[ -r "$v" ]] || _bad "$key → $v is not readable"
  done
  if [[ "$OPS_MODE" == hosted ]]; then
    [[ -r "$OPS_SHARED/keys/mongo/keyfile" ]] || _bad "missing $OPS_SHARED/keys/mongo/keyfile"
    [[ -n "$(env_get REDIS_PASSWORD)" ]] || _bad "REDIS_PASSWORD is not set (the hosted Redis requires one)"
  fi

  echo
  if ((problems)); then
    fail "$problems problem(s), $warnings warning(s)"
    return 1
  fi
  ok "env file looks right ($warnings warning(s))"
}
