#!/usr/bin/env bash
# Graft — wrapper around the official mongo image's entrypoint (GRAFT-09).
#
# mongod validates --keyFile with its own stat-based permission check, and that
# check fails with "bad file" (InvalidPath) against a bind-mounted path on this
# Docker/overlay2 combination — reproducible even at the correct 600 mode, for
# both a single-file bind and a directory bind. Copying the key onto the
# container's own writable layer first sidesteps it entirely; the source
# keyfile (mounted read-only at /etc/graft/keys/keyfile, generated by
# scripts/setup-env.ts) never leaves this container either way.
#
# Owned by mongodb:mongodb, not root: docker-entrypoint.sh re-execs itself as
# `gosu mongodb` before ever starting mongod, and a 600 file this script (root)
# just created would be unreadable to that user otherwise.
set -euo pipefail

install -o mongodb -g mongodb -m 600 /etc/graft/keys/keyfile /tmp/graft-mongo-keyfile

exec docker-entrypoint.sh "$@"
